import json
from groq import Groq

from config import GROQ_API_KEY
from utils import logger

# Initialize Groq client using the API key from .env
client = Groq(api_key=GROQ_API_KEY)


def generate_image_prompts(scene_plan):
    """
    Generate AI image prompts from the scene plan.

    Args:
        scene_plan (list): Scene plan generated by scene_planner.py

    Returns:
        list: List of image prompt dictionaries.
    """

    logger.info("Generating Image Prompts...")

    prompt = f"""
You are a professional cinematic concept artist.

Convert every scene into one highly detailed AI image generation prompt.

Requirements:

- Ultra realistic
- Cinematic lighting
- HDR
- 8K quality
- Highly detailed
- Professional composition
- Vibrant colors
- No copyrighted characters
- No watermark
- No text inside image

Scene Plan:

{json.dumps(scene_plan, indent=2)}

Return ONLY valid JSON.

Example format:

[
  {{
    "scene": 1,
    "prompt": "Ultra realistic futuristic AI laboratory with glowing holograms, cinematic lighting, HDR, 8K, highly detailed, professional composition"
  }},
  {{
    "scene": 2,
    "prompt": "Modern YouTube studio with multiple monitors displaying AI dashboards, dramatic lighting, HDR, 8K"
  }}
]
"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7
        )

        content = response.choices[0].message.content.strip()

        logger.info("Image prompts generated successfully.")

        return json.loads(content)

    except json.JSONDecodeError:
        logger.error("Groq returned invalid JSON.")
        print("\n========== RAW RESPONSE ==========\n")
        print(content)
        print("\n==================================\n")
        raise

    except Exception as e:
        logger.error(f"Error generating image prompts: {e}")
        raise